module.exports = {
    beforeEach: browser => {
        browser.url('http://localhost:3000/')
    },
    after: browser => {
        browser.end()
    },
    'NavigateListAndCheckIfContainsID': browser => {
        browser
            .click('li[name="employee1"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 1")
            .pause(1000)
            //
            .click('li[name="employee2"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 2")
            .pause(1000)
            //
            .click('li[name="employee3"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 3")
            .pause(1000)
            //
            //
            .click('li[name="employee4"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 4")
            .pause(1000)
            //
            .click('li[name="employee5"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 5")
            .pause(1000)
            //
            .click('li[name="employee6"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 6")
            .pause(1000)
            //
            .click('li[name="employee7"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 7")
            .pause(1000)
            //
            .click('li[name="employee8"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 8")
            .pause(1000)
            //
            .click('li[name="employee9"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 9")
            .pause(1000)
            //
            .click('li[name="employee10"]')
            .pause(1000)
            .assert.containsText('#employeeID', "ID: 10")
            .pause(1000)
    },
    'EditingEmployeesAndSaving': browser => {
        browser
            .click('li[name="employee1"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee2"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee3"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee4"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee5"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee6"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee7"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee8"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee9"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)
            .click('li[name="employee10"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .click('#saveBtn')
            .pause(1000)

    },
    'EditingAndCanceling': browser => {
        browser
            .click('li[name="employee1"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee2"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee3"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee4"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee5"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee6"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee7"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee8"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee9"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
            .click('li[name="employee10"]')
            .pause(1000)
            .click('input[name="nameEntry"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', "Carlos Lozano")
            .pause(1000)
            .click('input[name="phoneEntry"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', "3053030247")
            .click('.neutralButton')
            .pause(1000)
    }
}